name: Build+Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t kristaxox/wg-docker:latest .
      - name: Test 
        run: ./test/test.sh